image: node:latest

cache:
  paths:
    - ./node_modules/

before_script:
  - rm -rf build
  - rm -rf public
  - CI=false npm install

pages:
  stage: deploy
  script:
  - CI=false npm run build
  - mv build public

  artifacts:
    paths:
    - public
  only:
  - master
