image: node:latest

cache:
  paths:
    - ./node_modules/
    - .cache/
    - public/

stages:
    - deploy

pages:
  stage: deploy
  script:
  - npm install
  - npm run-script build
  - rm -rf ../public/*
  - mv ./build/* ../public/

  artifacts:
    paths:
    - public
  only:
  - master
